# key figures for the presentations to colaborators 
# relies on the workspace generated by _figures.qmd

ggplot(data=df,aes(NO3_mgl,NO3_Load_kgN_y))+ 
  geom_point(data=df,aes(size=Q_m3d),fill="grey",pch=21)+
  scale_fill_gradient(low = "yellow", high = "red",name = "NO3 (mg/L)", trans = log10_trans(),
                      breaks = log10breaks)+
  geom_text_repel(data=df_DER %>% na.omit(),aes(label=DERname),bg.color = "white",
                  bg.r = 0.25,size=3,color="blue",segment.color="blue")+
  xscale+
  yscale+
  #facet_wrap(vars(TOWN))+
  annotation_logticks()+
  theme_bw()
x = "load_vs_C"
ggsave(paste0("_fig_",x,".png"))

ggplot(data=df,aes(Q_m3d,NO3_Load_kgN_y))+ 
  geom_point(data=df,aes(size=NO3_mgl,fill=NO3_mgl),pch=21)+
  scale_fill_gradient(low = "yellow", high = "red",name = "NO3 (mg/L)", trans = log10_trans(),
                      breaks = log10breaks)+
  geom_text_repel(data=df_DER %>% na.omit(),aes(label=DERname),bg.color = "white",
                  bg.r = 0.25,size=3,color="blue",segment.color="blue")+
  xscale+
  yscale+
  #facet_wrap(vars(TOWN))+
  annotation_logticks()+
  theme_bw()
x = "load_vs_Q"
ggsave(paste0("_fig_",x,".png"))

ggplot(data=df,aes(Q_m3d,NO3_removal_kgN_y_walton2020_a))+ 
  geom_point(data=df,aes(size=bogsurf_area_ha,fill=NO3_mgl),pch=21)+
  scale_fill_gradient(low = "yellow", high = "red",name = "NO3 (mg/L)", trans = log10_trans(),
                      breaks = log10breaks)+
  geom_text_repel(data=df_DER %>% na.omit(),aes(label=DERname),bg.color = "white",
                  bg.r = 0.25,size=3,color="blue",segment.color="blue")+
  #facet_wrap(vars(TOWN))+
  xscale+
  yscale+
  annotation_logticks()+
  theme_bw()
x = "reduction_a_vs_Q_A_C"
ggsave(paste0("_fig_",x,".png"))

ggplot(data=df,aes(Q_m3d,NO3_removal_kgN_y_walton2020_b))+ 
  geom_point(data=df,aes(size=bogsurf_area_ha,fill=NO3_mgl),pch=21)+
  scale_fill_gradient(low = "yellow", high = "red",name = "NO3 (mg/L)", trans = log10_trans(),
                      breaks = log10breaks)+
  geom_text_repel(data=df_DER %>% na.omit(),aes(label=DERname),bg.color = "white",
                  bg.r = 0.25,size=3,color="blue",segment.color="blue")+
  #facet_wrap(vars(TOWN))+
  xscale+
  yscale+
  theme_bw()+
  annotation_logticks()
x = "reduction_b_vs_Q_A_C"
ggsave(paste0("_fig_",x,".png"))

ggplot(data=df,aes(NO3_Load_kgN_y,NO3_removal_kgN_y_walton2020_b))+ 
  geom_point(data=df,aes(size=HLR_md),fill="#FF7C7C",pch=21)+
  #scale_fill_gradient(low = "yellow", high = "red",name = "NO3 (mg/L)", trans = log10_trans(),
  #                    breaks = log10breaks)+
  #geom_text_repel(data=df_DER %>% na.omit(),aes(label=DERname),bg.color = "white",
  #                bg.r = 0.25,size=3,color="blue",segment.color="blue")+
  #facet_wrap(vars(TOWN))+
  xscale+
  yscale+
  theme_bw()+
  annotation_logticks()
x = "reduction_b_vs_load"
ggsave(paste0("_fig_",x,".png"))

ggplot(data=df,aes(NO3_Load_kgN_y,NO3_removal_kgN_y_walton2020_a))+ 
  geom_point(data=df,aes(size=HLR_md),fill="#7C7CFF",pch=21)+
  #scale_fill_gradient(low = "yellow", high = "red",name = "NO3 (mg/L)", trans = log10_trans(),
  #                    breaks = log10breaks)+
  #geom_text_repel(data=df_DER %>% na.omit(),aes(label=DERname),bg.color = "white",
  #                bg.r = 0.25,size=3,color="blue",segment.color="blue")+
  #facet_wrap(vars(TOWN))+
  xscale+
  yscale+
  theme_bw()+
  annotation_logticks()
x = "reduction_a_vs_load"
ggsave(paste0("_fig_",x,".png"))

g + geom_histogram(aes(x=NO3_mgl),fill='grey') + xscale + theme_bw()
x = "hist_NO3"
ggsave(paste0("_fig_",x,".png"))
g + geom_histogram(aes(x=Q_bogshed_m3d),fill='grey') +xscale+ theme_bw()
x = "hist_Q"
ggsave(paste0("_fig_",x,".png"))

g + geom_histogram(aes(x=NO3_mgl),fill='magenta',alpha=0.5) + 
  geom_histogram(aes(x=Q_m3d),fill='cyan',alpha=0.5) + 
  xscale + 
  theme_bw()+
  annotation_logticks(sides="b")
x = "hist_NO3_Q"
ggsave(paste0("_fig_",x,".png"))

